spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: hahaguazi311
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    #需要配合mandatory一起使用
    #publisher-returns: true
    #template:
    #  mandatory: true
datasource:
  write:
    url: jdbc:mysql://127.0.0.1:3306/master?useUnicode=true&characterEncoding=utf8
    username: root
    password: xxx
  read:
    url: jdbc:mysql://127.0.0.1:3306/slave?useUnicode=true&characterEncoding=utf8
    username: root
    password: xxx